# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['time_tracker.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config.py', '.'),
        ('logger.py', '.'),
        ('data_manager.py', '.'),
        ('analytics.py', '.'),
        ('settings_manager.py', '.'),
        ('time_logs.csv', '.'),
        ('tasks.csv', '.'),
    ],
    hiddenimports=[
        'streamlit',
        'pandas',
        'plotly',
        'numpy',
        'datetime',
        'csv',
        'json',
        'pathlib',
        'fcntl',
        'tempfile',
        'shutil',
        'threading',
        'time',
        'os',
        'sys',
        'webbrowser',
        'subprocess',
        'logging',
        'typing',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='TimeTrackerPro',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico' if os.path.exists('icon.ico') else None,
)
